# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6cff4e2472d784ae9f07d3350e3eded6c20755ff9a5332be6a4c54b3878642c05cf04c1a62ccde536f728565e449303231b8c6b7673eeba04811e0cdd536b34

test:
  secret_key_base: e12c48cd7ff6e3158db817291f93281539d6171b9e71f00b5ac2972e562b6656cf50bbc4c61fbe06d829ca2c56f7917c51e3cdd0ef2d227d8a8f6df7390f9975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
